### ISSUE TITLE
Cannot load all modules

### ISSUE THREAD

**Issue by Sambrog** [WenChentao/3DeeCellTracker#1]
Hi, I'm trying to use 3DeeCellTracker on a macOS device, but without succes yet.
I'm running into problems with installing the correct module/packages.

What I've tried so far is:
- installing anaconda
- opening a terminal, setting the working directory to the 3DeeCellTracker-master folder that I downloaded
- running `conda env create -f 3DCT.yml` gives me problems though.
        It cannot install/find the `keras-gpu=2.2.4`, and `tensorflow-gpu=1.14.0`.
- After some digging on stackoverflow I changed the 3DCT.yml contents by moving keras and tensorflow under the pip header as: `keras-gpu==2.2.4` and `tensorflow-gpu==1.14.0`. Yet this didn't solve the issue.

Any advice on how to solve the issue would be greatly appreaciated!

**Comment by WenChentao** [comment]
I will close this issue since it has been solved.
