### ISSUE TITLE
Error while tracking cells in ensemble mode

### ISSUE THREAD

**Issue by clarenzheng** [WenChentao/3DeeCellTracker#12]
Hello,

When I try to track a volume series of cells in StarDist ensemble mode, I run into the following error (see attached). 
[track_stardist_ensemble_mode error.txt](https://github.com/WenChentao/3DeeCellTracker/files/11970543/track_stardist_ensemble_mode.error.txt)

Please let me know if you have any clues. My volumes are of the shape (512, 1024, 26). Thank you!

**Comment by WenChentao** [comment]
According to the error message:
> ValueError: shape mismatch: objects cannot be broadcast to a single shape.  Mismatch is between arg 0 with shape (168, 401, 26) and arg 1 with shape (168, 401, 128).

I think you used the segmentation results I provided for the example data, which has a shape of (168, 401, 128). Could you please confirm whether you mixed your data with the example data?

**Comment by clarenzheng** [comment]
Hi,

Yes, it turns out I mixed the files. Thanks.
