### ISSUE TITLE
3DCT.yml file not found

### ISSUE THREAD

**Issue by mto17017** [WenChentao/3DeeCellTracker#17]
I installed all the required software. 
I followed the protocol for version 0.4. cd to the 3DeeCellTracker-master directory. 
The I entered the command conda env create -f 3DCT.yml
But it shows '/home/lee/Downloads/3DeeCellTracker-master/3DCT.yml' file not found
The repository in the tutorial shows a 3DCT.yml file but the actual repository has no such files. 
How do I solve this?

**Comment by WenChentao** [comment]
Version 0.4 is outdated. I recommend installing v1.0.0 instead. If you really want to try v0.4, you can find the YAML file here:
https://github.com/WenChentao/3DeeCellTracker/blob/3f09806a5d58cf4447a0c0adfa236dbdce281880/3DCT.yml.

**Comment by mto17017** [comment]
Thank you for your quick response @WenChentao. I tried installing the updated version but it is showing an error of : 

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

I tried implementing a disabling of auto save, but the error still remained. 

The code is still the same as your specifications.

%load_ext autoreload
%autoreload 2
import os
import warnings
warnings.filterwarnings('ignore')
from CellTracker.unet3d import TrainingUNet3D, unet3_a
%matplotlib inline

We also do not receive the dialog message: " Using Tensorflow Backend" 

I also used reload_ext autoreload, and that seems to allow  the code to work, however, the " Using Tensorflow Backend"  message still does not show. 

Please do advise me as to how I can resolve this. 

Best Regards

**Comment by WenChentao** [comment]
It seems you are using notebooks with 3D U-Net. I recommend using StarDist, which is available starting from version 1.0.

Regarding the autoreload extension error, you can simply remove these two lines:
```
%load_ext autoreload
%autoreload 2
```
Since the yml issue has been solved, I will close this issue. Please create a new issue if you encounter new problems.
