### ISSUE TITLE
Error while tracking cells in ensemble mode

### ISSUE THREAD

**Issue by hase-go** [WenChentao/3DeeCellTracker#18]
Hi,

When I tried to track my volumes series using ensemble mode, I run into the following error(see attached).

[error_ensemblemode.txt](https://github.com/user-attachments/files/18217005/error_ensemblemode.txt)

I thought the original volume data contained missing values, so I checked it, but it seems there aren't any. Please let me know if you have any clues, thanks!

**Comment by WenChentao** [comment]
Could you share the values of `t` and `confirmed_coord_t1.real`? You can check them with %debug

**Comment by hase-go** [comment]
Thank you for your reply. Here is what I got,

[t_confirmed_coord.txt](https://github.com/user-attachments/files/18224774/t_confirmed_coord.txt)

**Comment by WenChentao** [comment]
Uhmm, this is strange. It seems the cell coordinates at t=2 extracted during StarDist segmentation contain NaN values. I can't explain the reason without testing it with the actual data.

**Comment by hase-go** [comment]
I see. 
Looks like I don't get this type of error while using some other volume data. 
Is it possible that there were missing values in the raw data pixels? 
Or should I retrain another data for StarDist segmentation?

**Comment by WenChentao** [comment]
It is strange that StarDist generates NaN values for the segmented cells. I am not sure of the reason. Perhaps you could test whether the segmentation results contain NaN values for time points other than t=2. To do this, you can run the following code:
```
t = 1
coords_at_t = np.load(str(tracker.results_dir / "track_results" / "coords_real" / f"coords{str(t).zfill(6)}.npy"))
```
Try changing the value of t to see what happens.

**Comment by hase-go** [comment]
I only got "coords000001.npy" in "tracker.results_dir/track_results/coords_real/" and it also contained NaN values.

**Comment by hase-go** [comment]
Hi,
It turned out that I made the manual label so small that gaussian filtering erased it.
I guess that is why the segmentation results contained NaN values after `coords2image.interpolate(interpolation_factor=interpolation_factor)` .

Apologies for the trouble.
Thank you.
