### ISSUE TITLE
Track cells or nuclei?

### ISSUE THREAD

**Issue by haesleinhuepf** [WenChentao/3DeeCellTracker#2]
Hi @WenChentao ,

first of all congrats to this amazing project! Just a quick question: Can the software only track cell nuclei or can it also track whole cells, e.g. imaged with a membrane marker?

Thanks!

Best,
Robert

**Comment by WenChentao** [comment]
> Hi @WenChentao ,
> 
> first of all congrats to this amazing project! Just a quick question: Can the software only track cell nuclei or can it also track whole cells, e.g. imaged with a membrane marker?
> 
> Thanks!
> 
> Best, Robert

Thank you for asking. We did not test it with membrane images, but logically it should be possible to segment cells if the training data with cell/non-cell regions annotated are prepared. Could you upload an example of the membrane image?
