### ISSUE TITLE
Available pretrained model

### ISSUE THREAD

**Issue by ss8319** [WenChentao/3DeeCellTracker#3]
Hi, I was wondering if there are any U-Net or FFN pretrained models that are available to be downloaded instead of training our own U-Net with the given dataset?

**Comment by WenChentao** [comment]
I have included the pretrained models of U-Net and FFN in the demo data from https://osf.io/dt76c/. 

You could reuse the pre-trained FFN model for new data. But the pretrained U-Net usually does not work well for new imaging conditions. You should train it with your own data.

**Comment by ss8319** [comment]
Thank you! @WenChentao
