### ISSUE TITLE
Error in Training 3D_U_Net_training-clear.ipynb 

### ISSUE THREAD

**Issue by ss8319** [WenChentao/3DeeCellTracker#4]
I downloaded the training demo data set as suggested- "The demo data can be found in the "unet_training" folder downloaded from https://osf.io/dt76c/"

Running the corresponding line in the notebook:
trainer.load_dataset()

gives error:
[/usr/local/lib/python3.7/dist-packages/CellTracker/preprocess.py](https://localhost:8080/#) in load_image(folder_path, print_)
     76     for img_path in img_file_path:
     77         img.append(cv2.imread(img_path, -1))
---> 78     img_array = np.array(img).transpose((1, 2, 0))
     79     if print_:
     80         print("Load images with shape:", img_array.shape)

ValueError: axes don't match array

**Comment by WenChentao** [comment]
Could you let me know which notebook did you test? Please also tell me the parameters you have used, and the paths of your data.

**Comment by ss8319** [comment]
Hi @WenChentao I used the 3D_U_Net_training-clear.ipynb notebook. The parameters are set to the 'default' as in the notebook. I think the error arises when I run the part C. Load the train / validation datasets. Specifically the line - trainer.load_dataset()

I downloaded the demo data (https://osf.io/dt76c/) and put the corresponding files in unet_01/train_image, unet_01/train_label, unet_01/valid_image and unet_01/valid_label respectively. I am running the notebook in Google Colab to use their GPUs.

**Comment by WenChentao** [comment]
@ss8319 Thank you for reporting. I have not tested our programs in Google Colab. I will do it later.

**Comment by WenChentao** [comment]
I tested the notebook in Google Colab, and it worked after modifications of working directory. Could you confirm following two things:
1. The folder unet_01 should be under the current working directory. If it is not, you need to change the working directory by os.chdir("xxx"), replacing xxx with the parent directory of unet_01.
2. The images should be stored under each folder such as:
unet_01/train_image/img0001.tif, unet_01/train_image/img0002.tif, etc.

**Comment by WenChentao** [comment]
Since there is no further feedback, I will close this issue.
