### ISSUE TITLE
String Formatting error | ensemble_mode_worm4-clear.ipynb

### ISSUE THREAD

**Issue by ss8319** [WenChentao/3DeeCellTracker#5]
Hi. I am running the code in the notebook- ensemble_mode_worm4-clear.ipynb on Google Colab.

I ran the steps as told with only modifications in B. Initialize the parameters for tracking.

My code: 
```
tracker = Tracker(
    volume_num=64, siz_xyz=(512,512,5), z_xy_ratio=1, z_scaling=1, miss_frame=[],
    noise_level=200, min_size=50, beta_tk=1000, lambda_tk=0.00001, maxiter_tk=10, ensemble=20,
    folder_path=os.path.abspath("./worm4"), image_name="movie.tif", unet_model_file="unet3_pretrained_worm4.h5",ffn_model_file="ffn_pretrained.h5")
```

I loaded the pretrained models provided in the following directories. /content/worm4/models/ffn_pretrained.h5 and /content/worm4/models/unet3_pretrained_worm4.h5. My file- movie.tif is stem cell movie on the shape (64, 5, 2, 512, 512). 64 frames(time instances), 5 stacks,  2 channels and X=512 , Y=512.

I have done part C as specified in the notebook:
Move images to the created "/data" folder. The names of the images should be consistent with the parameter "image_name"
Move the pre-trained 3D U-Net and FFN model files to the created "/models" folder

In part D, I am getting the error as follows:
```
WARNING:tensorflow:No` training configuration found in the save file, so the model was *not* compiled. Compile it manually.
Loaded the 3D U-Net model
path: /content/worm4/data/
name: movie.tif
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-20-776d55c76e6d>](https://localhost:8080/#) in <module>()
      1 tracker.load_unet()
----> 2 tracker.segment_vol1()

2 frames
[/usr/local/lib/python3.7/dist-packages/CellTracker/tracker.py](https://localhost:8080/#) in read_image_ts(vol, path, name, z_range, print_)
    136     print("name:",name)
    137     for z in range(z_range[0], z_range[1]):
--> 138         image_raw.append(cv2.imread(path + name %(vol, z), -1))
    139     img_array = np.array(image_raw).transpose((1, 2, 0))
    140     if print_:

TypeError: not all arguments converted during string formatting
```

**Comment by WenChentao** [comment]
@ss8319 Thank you for asking. 3DeeCellTracker currently only accepts 2D grayscale image sequences (with TIFF format) as input. So, please transform your movie.tif to 2D images and select to use one of the channels.
You can check our demo data to get an impression of the data format.

**Comment by WenChentao** [comment]
I will close this issue since there is no further feedback.
